// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema_showing.proto

package cinema_showing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCinemaShowingRequest struct {
	Movie                int64    `protobuf:"varint,1,opt,name=movie,proto3" json:"movie,omitempty"`
	CinemaHall           int64    `protobuf:"varint,2,opt,name=cinemaHall,proto3" json:"cinemaHall,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaShowingRequest) Reset()         { *m = CreateCinemaShowingRequest{} }
func (m *CreateCinemaShowingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaShowingRequest) ProtoMessage()    {}
func (*CreateCinemaShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{0}
}

func (m *CreateCinemaShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaShowingRequest.Unmarshal(m, b)
}
func (m *CreateCinemaShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaShowingRequest.Marshal(b, m, deterministic)
}
func (m *CreateCinemaShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaShowingRequest.Merge(m, src)
}
func (m *CreateCinemaShowingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaShowingRequest.Size(m)
}
func (m *CreateCinemaShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaShowingRequest proto.InternalMessageInfo

func (m *CreateCinemaShowingRequest) GetMovie() int64 {
	if m != nil {
		return m.Movie
	}
	return 0
}

func (m *CreateCinemaShowingRequest) GetCinemaHall() int64 {
	if m != nil {
		return m.CinemaHall
	}
	return 0
}

type CreateCinemaShowingResponse struct {
	Showing              *CinemaShowing `protobuf:"bytes,1,opt,name=showing,proto3" json:"showing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateCinemaShowingResponse) Reset()         { *m = CreateCinemaShowingResponse{} }
func (m *CreateCinemaShowingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaShowingResponse) ProtoMessage()    {}
func (*CreateCinemaShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{1}
}

func (m *CreateCinemaShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaShowingResponse.Unmarshal(m, b)
}
func (m *CreateCinemaShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaShowingResponse.Marshal(b, m, deterministic)
}
func (m *CreateCinemaShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaShowingResponse.Merge(m, src)
}
func (m *CreateCinemaShowingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaShowingResponse.Size(m)
}
func (m *CreateCinemaShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaShowingResponse proto.InternalMessageInfo

func (m *CreateCinemaShowingResponse) GetShowing() *CinemaShowing {
	if m != nil {
		return m.Showing
	}
	return nil
}

type DeleteCinemaShowingRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaShowingRequest) Reset()         { *m = DeleteCinemaShowingRequest{} }
func (m *DeleteCinemaShowingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaShowingRequest) ProtoMessage()    {}
func (*DeleteCinemaShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{2}
}

func (m *DeleteCinemaShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaShowingRequest.Unmarshal(m, b)
}
func (m *DeleteCinemaShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaShowingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCinemaShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaShowingRequest.Merge(m, src)
}
func (m *DeleteCinemaShowingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaShowingRequest.Size(m)
}
func (m *DeleteCinemaShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaShowingRequest proto.InternalMessageInfo

func (m *DeleteCinemaShowingRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaShowingResponse struct {
	Showing              *CinemaShowing `protobuf:"bytes,1,opt,name=showing,proto3" json:"showing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteCinemaShowingResponse) Reset()         { *m = DeleteCinemaShowingResponse{} }
func (m *DeleteCinemaShowingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaShowingResponse) ProtoMessage()    {}
func (*DeleteCinemaShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{3}
}

func (m *DeleteCinemaShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaShowingResponse.Unmarshal(m, b)
}
func (m *DeleteCinemaShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaShowingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCinemaShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaShowingResponse.Merge(m, src)
}
func (m *DeleteCinemaShowingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaShowingResponse.Size(m)
}
func (m *DeleteCinemaShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaShowingResponse proto.InternalMessageInfo

func (m *DeleteCinemaShowingResponse) GetShowing() *CinemaShowing {
	if m != nil {
		return m.Showing
	}
	return nil
}

type FindAllCinemaShowingsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllCinemaShowingsRequest) Reset()         { *m = FindAllCinemaShowingsRequest{} }
func (m *FindAllCinemaShowingsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllCinemaShowingsRequest) ProtoMessage()    {}
func (*FindAllCinemaShowingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{4}
}

func (m *FindAllCinemaShowingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllCinemaShowingsRequest.Unmarshal(m, b)
}
func (m *FindAllCinemaShowingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllCinemaShowingsRequest.Marshal(b, m, deterministic)
}
func (m *FindAllCinemaShowingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllCinemaShowingsRequest.Merge(m, src)
}
func (m *FindAllCinemaShowingsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllCinemaShowingsRequest.Size(m)
}
func (m *FindAllCinemaShowingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllCinemaShowingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllCinemaShowingsRequest proto.InternalMessageInfo

type FindAllCinemaShowingsResponse struct {
	Showings             []*CinemaShowing `protobuf:"bytes,1,rep,name=showings,proto3" json:"showings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FindAllCinemaShowingsResponse) Reset()         { *m = FindAllCinemaShowingsResponse{} }
func (m *FindAllCinemaShowingsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllCinemaShowingsResponse) ProtoMessage()    {}
func (*FindAllCinemaShowingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{5}
}

func (m *FindAllCinemaShowingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllCinemaShowingsResponse.Unmarshal(m, b)
}
func (m *FindAllCinemaShowingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllCinemaShowingsResponse.Marshal(b, m, deterministic)
}
func (m *FindAllCinemaShowingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllCinemaShowingsResponse.Merge(m, src)
}
func (m *FindAllCinemaShowingsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllCinemaShowingsResponse.Size(m)
}
func (m *FindAllCinemaShowingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllCinemaShowingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllCinemaShowingsResponse proto.InternalMessageInfo

func (m *FindAllCinemaShowingsResponse) GetShowings() []*CinemaShowing {
	if m != nil {
		return m.Showings
	}
	return nil
}

type FindCinemaShowingRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindCinemaShowingRequest) Reset()         { *m = FindCinemaShowingRequest{} }
func (m *FindCinemaShowingRequest) String() string { return proto.CompactTextString(m) }
func (*FindCinemaShowingRequest) ProtoMessage()    {}
func (*FindCinemaShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{6}
}

func (m *FindCinemaShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCinemaShowingRequest.Unmarshal(m, b)
}
func (m *FindCinemaShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCinemaShowingRequest.Marshal(b, m, deterministic)
}
func (m *FindCinemaShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCinemaShowingRequest.Merge(m, src)
}
func (m *FindCinemaShowingRequest) XXX_Size() int {
	return xxx_messageInfo_FindCinemaShowingRequest.Size(m)
}
func (m *FindCinemaShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCinemaShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindCinemaShowingRequest proto.InternalMessageInfo

func (m *FindCinemaShowingRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindCinemaShowingResponse struct {
	Showing              *CinemaShowing `protobuf:"bytes,1,opt,name=showing,proto3" json:"showing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindCinemaShowingResponse) Reset()         { *m = FindCinemaShowingResponse{} }
func (m *FindCinemaShowingResponse) String() string { return proto.CompactTextString(m) }
func (*FindCinemaShowingResponse) ProtoMessage()    {}
func (*FindCinemaShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{7}
}

func (m *FindCinemaShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCinemaShowingResponse.Unmarshal(m, b)
}
func (m *FindCinemaShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCinemaShowingResponse.Marshal(b, m, deterministic)
}
func (m *FindCinemaShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCinemaShowingResponse.Merge(m, src)
}
func (m *FindCinemaShowingResponse) XXX_Size() int {
	return xxx_messageInfo_FindCinemaShowingResponse.Size(m)
}
func (m *FindCinemaShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCinemaShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindCinemaShowingResponse proto.InternalMessageInfo

func (m *FindCinemaShowingResponse) GetShowing() *CinemaShowing {
	if m != nil {
		return m.Showing
	}
	return nil
}

type CinemaShowing struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie                int64    `protobuf:"varint,2,opt,name=movie,proto3" json:"movie,omitempty"`
	CinemaHall           int64    `protobuf:"varint,3,opt,name=cinemaHall,proto3" json:"cinemaHall,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaShowing) Reset()         { *m = CinemaShowing{} }
func (m *CinemaShowing) String() string { return proto.CompactTextString(m) }
func (*CinemaShowing) ProtoMessage()    {}
func (*CinemaShowing) Descriptor() ([]byte, []int) {
	return fileDescriptor_50fce743d1c301cd, []int{8}
}

func (m *CinemaShowing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaShowing.Unmarshal(m, b)
}
func (m *CinemaShowing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaShowing.Marshal(b, m, deterministic)
}
func (m *CinemaShowing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaShowing.Merge(m, src)
}
func (m *CinemaShowing) XXX_Size() int {
	return xxx_messageInfo_CinemaShowing.Size(m)
}
func (m *CinemaShowing) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaShowing.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaShowing proto.InternalMessageInfo

func (m *CinemaShowing) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CinemaShowing) GetMovie() int64 {
	if m != nil {
		return m.Movie
	}
	return 0
}

func (m *CinemaShowing) GetCinemaHall() int64 {
	if m != nil {
		return m.CinemaHall
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateCinemaShowingRequest)(nil), "CreateCinemaShowingRequest")
	proto.RegisterType((*CreateCinemaShowingResponse)(nil), "CreateCinemaShowingResponse")
	proto.RegisterType((*DeleteCinemaShowingRequest)(nil), "DeleteCinemaShowingRequest")
	proto.RegisterType((*DeleteCinemaShowingResponse)(nil), "DeleteCinemaShowingResponse")
	proto.RegisterType((*FindAllCinemaShowingsRequest)(nil), "FindAllCinemaShowingsRequest")
	proto.RegisterType((*FindAllCinemaShowingsResponse)(nil), "FindAllCinemaShowingsResponse")
	proto.RegisterType((*FindCinemaShowingRequest)(nil), "FindCinemaShowingRequest")
	proto.RegisterType((*FindCinemaShowingResponse)(nil), "FindCinemaShowingResponse")
	proto.RegisterType((*CinemaShowing)(nil), "CinemaShowing")
}

func init() { proto.RegisterFile("cinema_showing.proto", fileDescriptor_50fce743d1c301cd) }

var fileDescriptor_50fce743d1c301cd = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4d, 0x6b, 0xb3, 0x40,
	0x14, 0x85, 0x51, 0xdf, 0xd7, 0x94, 0x5b, 0x9a, 0xc5, 0xe0, 0xc2, 0x8c, 0x46, 0x82, 0xab, 0x10,
	0xca, 0x5d, 0xa4, 0xeb, 0x2e, 0x8a, 0xfd, 0x08, 0x74, 0x67, 0xe8, 0xba, 0xd8, 0x78, 0x69, 0x07,
	0x8c, 0xa6, 0x8e, 0x4d, 0x7f, 0x53, 0xff, 0x65, 0x51, 0xa7, 0x1f, 0x06, 0x47, 0x9a, 0x65, 0x72,
	0x0e, 0xe7, 0xdc, 0xe1, 0x39, 0x82, 0xb3, 0x11, 0x39, 0x6d, 0x93, 0x47, 0xf9, 0x52, 0xbc, 0x8b,
	0xfc, 0x19, 0x77, 0x65, 0x51, 0x15, 0x61, 0x0c, 0x3c, 0x2a, 0x29, 0xa9, 0x28, 0x6a, 0xd4, 0x75,
	0x2b, 0xc6, 0xf4, 0xfa, 0x46, 0xb2, 0x62, 0x0e, 0xfc, 0xdf, 0x16, 0x7b, 0x41, 0xae, 0x31, 0x33,
	0xe6, 0x56, 0xdc, 0xfe, 0x60, 0x01, 0x40, 0x9b, 0xb5, 0x4a, 0xb2, 0xcc, 0x35, 0x1b, 0xe9, 0xd7,
	0x3f, 0xe1, 0x1d, 0x78, 0xbd, 0x99, 0x72, 0x57, 0xe4, 0x92, 0xd8, 0x1c, 0x46, 0xea, 0x86, 0x26,
	0xf6, 0x74, 0x39, 0xc6, 0xae, 0xf1, 0x4b, 0x0e, 0xcf, 0x81, 0x5f, 0x53, 0x46, 0x9a, 0xe3, 0xc6,
	0x60, 0x8a, 0x54, 0x5d, 0x66, 0x8a, 0xb4, 0xae, 0xed, 0x75, 0x1f, 0x5d, 0x1b, 0x80, 0x7f, 0x2b,
	0xf2, 0xf4, 0x2a, 0xcb, 0x3a, 0x06, 0xa9, 0x8a, 0xc3, 0x7b, 0x98, 0x6a, 0x74, 0x55, 0xb5, 0x80,
	0x13, 0x95, 0x25, 0x5d, 0x63, 0x66, 0xf5, 0x74, 0x7d, 0xeb, 0xe1, 0x02, 0xdc, 0x3a, 0xec, 0x4f,
	0x2f, 0xbc, 0x81, 0x49, 0x8f, 0xf7, 0xe8, 0xf7, 0x3d, 0xc0, 0x59, 0x47, 0x39, 0xec, 0xf9, 0xc1,
	0x6e, 0xea, 0xb1, 0x5b, 0x87, 0xd8, 0x97, 0x1f, 0x26, 0x38, 0x9d, 0xdc, 0x35, 0x95, 0x7b, 0xb1,
	0x21, 0x16, 0x81, 0xdd, 0xee, 0x81, 0x79, 0xa8, 0x1f, 0x1b, 0xf7, 0x71, 0x68, 0x35, 0x11, 0xd8,
	0x2d, 0x5d, 0xe6, 0xa1, 0x7e, 0x14, 0xdc, 0xc7, 0xa1, 0x0d, 0xac, 0x60, 0xa4, 0xc8, 0xb1, 0x29,
	0x0e, 0x31, 0xe6, 0x01, 0x0e, 0x23, 0xbe, 0x84, 0x7f, 0xb5, 0x81, 0x4d, 0x50, 0x47, 0x8f, 0x73,
	0xd4, 0xc2, 0x7a, 0xb2, 0x9b, 0xaf, 0xef, 0xe2, 0x33, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xeb, 0x7e,
	0xbd, 0x95, 0x03, 0x00, 0x00,
}
