// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindAllUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllUsersRequest) Reset()         { *m = FindAllUsersRequest{} }
func (m *FindAllUsersRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllUsersRequest) ProtoMessage()    {}
func (*FindAllUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *FindAllUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllUsersRequest.Unmarshal(m, b)
}
func (m *FindAllUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllUsersRequest.Marshal(b, m, deterministic)
}
func (m *FindAllUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllUsersRequest.Merge(m, src)
}
func (m *FindAllUsersRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllUsersRequest.Size(m)
}
func (m *FindAllUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllUsersRequest proto.InternalMessageInfo

type FindAllUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllUsersResponse) Reset()         { *m = FindAllUsersResponse{} }
func (m *FindAllUsersResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllUsersResponse) ProtoMessage()    {}
func (*FindAllUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *FindAllUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllUsersResponse.Unmarshal(m, b)
}
func (m *FindAllUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllUsersResponse.Marshal(b, m, deterministic)
}
func (m *FindAllUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllUsersResponse.Merge(m, src)
}
func (m *FindAllUsersResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllUsersResponse.Size(m)
}
func (m *FindAllUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllUsersResponse proto.InternalMessageInfo

func (m *FindAllUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "DeleteUserResponse")
	proto.RegisterType((*FindAllUsersRequest)(nil), "FindAllUsersRequest")
	proto.RegisterType((*FindAllUsersResponse)(nil), "FindAllUsersResponse")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x18, 0x85, 0x69, 0xd7, 0x56, 0x3c, 0x03, 0x61, 0x7f, 0x3b, 0xa8, 0xf5, 0x66, 0xc4, 0x1b, 0xf5,
	0x22, 0xb2, 0x0d, 0xbc, 0x17, 0xc5, 0x07, 0xa8, 0xf8, 0x00, 0xd3, 0xfe, 0x17, 0x81, 0xda, 0xce,
	0x24, 0xf3, 0xa5, 0x7c, 0x49, 0x49, 0x5a, 0x70, 0x73, 0x81, 0xdd, 0xe5, 0x3f, 0x39, 0xf9, 0xc8,
	0x39, 0x3f, 0xb0, 0x33, 0xac, 0xe5, 0x56, 0xf7, 0xb6, 0x17, 0xb7, 0x98, 0x3d, 0x69, 0xde, 0x58,
	0x7e, 0x33, 0xac, 0x6b, 0xfe, 0xda, 0xb1, 0xb1, 0x54, 0x20, 0xb5, 0xca, 0xb6, 0x5c, 0x46, 0x8b,
	0xe8, 0xe6, 0xbc, 0x1e, 0x06, 0x71, 0x0f, 0xda, 0xb7, 0x9a, 0x6d, 0xdf, 0x19, 0xa6, 0x4b, 0x24,
	0x0e, 0xe7, 0xad, 0xd3, 0x55, 0x2a, 0xfd, 0xa5, 0x97, 0xc4, 0x35, 0x66, 0xcf, 0xdc, 0xf2, 0x21,
	0xfb, 0x02, 0xb1, 0x6a, 0xbc, 0x7b, 0x52, 0xc7, 0xaa, 0x71, 0xd4, 0x7d, 0xd3, 0x69, 0xea, 0x1c,
	0xf9, 0x8b, 0xea, 0x9a, 0xc7, 0xb6, 0x75, 0xa2, 0x19, 0xb9, 0x62, 0x8d, 0xe2, 0x50, 0x1e, 0x49,
	0x57, 0x48, 0xdd, 0x33, 0x53, 0x46, 0x8b, 0xc9, 0x1f, 0x6a, 0xd0, 0xc4, 0x1d, 0x12, 0x37, 0xfe,
	0xff, 0x14, 0x11, 0x92, 0x6e, 0xf3, 0xc9, 0x65, 0xec, 0xf3, 0xfb, 0xf3, 0xea, 0x27, 0xc2, 0xd4,
	0x99, 0x5f, 0x59, 0x7f, 0xab, 0x0f, 0xa6, 0x25, 0xb2, 0xa1, 0x0e, 0x22, 0x79, 0x54, 0x61, 0x95,
	0xcb, 0x40, 0x57, 0x4b, 0x64, 0x43, 0x56, 0x22, 0x79, 0xd4, 0x4c, 0x95, 0xcb, 0x40, 0x11, 0x0f,
	0x38, 0x1b, 0x63, 0x51, 0x21, 0x03, 0xb9, 0xab, 0xb9, 0x0c, 0xc5, 0x7e, 0xcf, 0xfc, 0x7a, 0xd7,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xc5, 0x9c, 0x5b, 0xec, 0x01, 0x00, 0x00,
}
