// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reservation.proto

package reservation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReservationRequest struct {
	Showing              int64    `protobuf:"varint,1,opt,name=showing,proto3" json:"showing,omitempty"`
	User                 int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReservationRequest) Reset()         { *m = CreateReservationRequest{} }
func (m *CreateReservationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReservationRequest) ProtoMessage()    {}
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{0}
}

func (m *CreateReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationRequest.Unmarshal(m, b)
}
func (m *CreateReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationRequest.Marshal(b, m, deterministic)
}
func (m *CreateReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationRequest.Merge(m, src)
}
func (m *CreateReservationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReservationRequest.Size(m)
}
func (m *CreateReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationRequest proto.InternalMessageInfo

func (m *CreateReservationRequest) GetShowing() int64 {
	if m != nil {
		return m.Showing
	}
	return 0
}

func (m *CreateReservationRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *CreateReservationRequest) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type CreateReservationResponse struct {
	Reservation          *Reservation `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateReservationResponse) Reset()         { *m = CreateReservationResponse{} }
func (m *CreateReservationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReservationResponse) ProtoMessage()    {}
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{1}
}

func (m *CreateReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationResponse.Unmarshal(m, b)
}
func (m *CreateReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationResponse.Marshal(b, m, deterministic)
}
func (m *CreateReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationResponse.Merge(m, src)
}
func (m *CreateReservationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReservationResponse.Size(m)
}
func (m *CreateReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationResponse proto.InternalMessageInfo

func (m *CreateReservationResponse) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type ConfirmReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmReservationRequest) Reset()         { *m = ConfirmReservationRequest{} }
func (m *ConfirmReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmReservationRequest) ProtoMessage()    {}
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{2}
}

func (m *ConfirmReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmReservationRequest.Unmarshal(m, b)
}
func (m *ConfirmReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmReservationRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmReservationRequest.Merge(m, src)
}
func (m *ConfirmReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmReservationRequest.Size(m)
}
func (m *ConfirmReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmReservationRequest proto.InternalMessageInfo

func (m *ConfirmReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConfirmReservationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConfirmReservationResponse struct {
	Reservation          *Reservation `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfirmReservationResponse) Reset()         { *m = ConfirmReservationResponse{} }
func (m *ConfirmReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmReservationResponse) ProtoMessage()    {}
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{3}
}

func (m *ConfirmReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmReservationResponse.Unmarshal(m, b)
}
func (m *ConfirmReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmReservationResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmReservationResponse.Merge(m, src)
}
func (m *ConfirmReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmReservationResponse.Size(m)
}
func (m *ConfirmReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmReservationResponse proto.InternalMessageInfo

func (m *ConfirmReservationResponse) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type DeleteReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationRequest) Reset()         { *m = DeleteReservationRequest{} }
func (m *DeleteReservationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationRequest) ProtoMessage()    {}
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{4}
}

func (m *DeleteReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationRequest.Unmarshal(m, b)
}
func (m *DeleteReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationRequest.Merge(m, src)
}
func (m *DeleteReservationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationRequest.Size(m)
}
func (m *DeleteReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationRequest proto.InternalMessageInfo

func (m *DeleteReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteReservationResponse struct {
	Reservation          *Reservation `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteReservationResponse) Reset()         { *m = DeleteReservationResponse{} }
func (m *DeleteReservationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationResponse) ProtoMessage()    {}
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{5}
}

func (m *DeleteReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationResponse.Unmarshal(m, b)
}
func (m *DeleteReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationResponse.Merge(m, src)
}
func (m *DeleteReservationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationResponse.Size(m)
}
func (m *DeleteReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationResponse proto.InternalMessageInfo

func (m *DeleteReservationResponse) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type FindAllReservationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllReservationsRequest) Reset()         { *m = FindAllReservationsRequest{} }
func (m *FindAllReservationsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllReservationsRequest) ProtoMessage()    {}
func (*FindAllReservationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{6}
}

func (m *FindAllReservationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllReservationsRequest.Unmarshal(m, b)
}
func (m *FindAllReservationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllReservationsRequest.Marshal(b, m, deterministic)
}
func (m *FindAllReservationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllReservationsRequest.Merge(m, src)
}
func (m *FindAllReservationsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllReservationsRequest.Size(m)
}
func (m *FindAllReservationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllReservationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllReservationsRequest proto.InternalMessageInfo

type FindAllReservationsResponse struct {
	Reservations         []*Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindAllReservationsResponse) Reset()         { *m = FindAllReservationsResponse{} }
func (m *FindAllReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllReservationsResponse) ProtoMessage()    {}
func (*FindAllReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{7}
}

func (m *FindAllReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllReservationsResponse.Unmarshal(m, b)
}
func (m *FindAllReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllReservationsResponse.Marshal(b, m, deterministic)
}
func (m *FindAllReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllReservationsResponse.Merge(m, src)
}
func (m *FindAllReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllReservationsResponse.Size(m)
}
func (m *FindAllReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllReservationsResponse proto.InternalMessageInfo

func (m *FindAllReservationsResponse) GetReservations() []*Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

type Reservation struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User                 int64    `protobuf:"varint,3,opt,name=user,proto3" json:"user,omitempty"`
	Showing              int64    `protobuf:"varint,4,opt,name=showing,proto3" json:"showing,omitempty"`
	Confirmed            bool     `protobuf:"varint,5,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,6,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{8}
}

func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reservation) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Reservation) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *Reservation) GetShowing() int64 {
	if m != nil {
		return m.Showing
	}
	return 0
}

func (m *Reservation) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *Reservation) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type Seat struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{9}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Seat) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateReservationRequest)(nil), "CreateReservationRequest")
	proto.RegisterType((*CreateReservationResponse)(nil), "CreateReservationResponse")
	proto.RegisterType((*ConfirmReservationRequest)(nil), "ConfirmReservationRequest")
	proto.RegisterType((*ConfirmReservationResponse)(nil), "ConfirmReservationResponse")
	proto.RegisterType((*DeleteReservationRequest)(nil), "DeleteReservationRequest")
	proto.RegisterType((*DeleteReservationResponse)(nil), "DeleteReservationResponse")
	proto.RegisterType((*FindAllReservationsRequest)(nil), "FindAllReservationsRequest")
	proto.RegisterType((*FindAllReservationsResponse)(nil), "FindAllReservationsResponse")
	proto.RegisterType((*Reservation)(nil), "Reservation")
	proto.RegisterType((*Seat)(nil), "Seat")
}

func init() { proto.RegisterFile("reservation.proto", fileDescriptor_c1b272c5347b2042) }

var fileDescriptor_c1b272c5347b2042 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x8e, 0xda, 0x30,
	0x10, 0xc6, 0x95, 0x84, 0x84, 0x32, 0x41, 0x55, 0x6b, 0xf5, 0xe0, 0x38, 0x1c, 0x50, 0x4e, 0x88,
	0x83, 0x55, 0xd1, 0x07, 0x40, 0x14, 0xd4, 0x4b, 0x2b, 0x55, 0x32, 0x4f, 0x90, 0x92, 0x69, 0x1b,
	0x6d, 0x36, 0x66, 0xed, 0x00, 0x2f, 0xb3, 0x87, 0x7d, 0xd4, 0x55, 0x9c, 0xec, 0x62, 0x56, 0x09,
	0x5a, 0x71, 0x9b, 0x7f, 0xf2, 0xf7, 0x31, 0xf3, 0x23, 0xf0, 0x59, 0xa1, 0x46, 0x75, 0x4c, 0xab,
	0x5c, 0x96, 0x7c, 0xaf, 0x64, 0x25, 0x13, 0x04, 0xba, 0x56, 0x98, 0x56, 0x28, 0xce, 0x2d, 0x81,
	0x0f, 0x07, 0xd4, 0x15, 0xa1, 0x30, 0xd4, 0xff, 0xe5, 0x29, 0x2f, 0xff, 0x51, 0x67, 0xea, 0xcc,
	0x3c, 0xf1, 0x92, 0x12, 0x02, 0x83, 0x83, 0x46, 0x45, 0x5d, 0x53, 0x36, 0x31, 0x89, 0xc1, 0xd7,
	0x98, 0x56, 0x9a, 0x7a, 0x53, 0x6f, 0x16, 0x2e, 0x7c, 0xbe, 0xc5, 0xb4, 0x12, 0x4d, 0x2d, 0xf9,
	0x09, 0x51, 0x87, 0x8c, 0xde, 0xcb, 0x52, 0x23, 0xe1, 0x10, 0x5a, 0xc6, 0x8c, 0x56, 0xb8, 0x18,
	0x73, 0x7b, 0xd4, 0x1e, 0x48, 0x56, 0x10, 0xad, 0x65, 0xf9, 0x37, 0x57, 0xf7, 0x1d, 0xa6, 0x3f,
	0x82, 0x9b, 0x67, 0xad, 0x5f, 0x37, 0xcf, 0xc8, 0x17, 0xf0, 0x2b, 0x79, 0x87, 0xa5, 0xf1, 0x3a,
	0x12, 0x4d, 0x92, 0xfc, 0x02, 0xd6, 0xf5, 0xc4, 0x8d, 0x86, 0xe6, 0x40, 0x37, 0x58, 0x60, 0xe7,
	0x12, 0xdf, 0xf8, 0xa9, 0x37, 0xd1, 0x31, 0x7b, 0xa3, 0xf0, 0x04, 0xd8, 0x8f, 0xbc, 0xcc, 0x56,
	0x45, 0x61, 0x8d, 0xe8, 0x56, 0x3a, 0xf9, 0x0d, 0x71, 0x67, 0xb7, 0x15, 0xfb, 0x0a, 0x63, 0xeb,
	0x2d, 0x4d, 0x1d, 0x73, 0xb7, 0x4b, 0xb5, 0x8b, 0x89, 0xe4, 0xd1, 0x81, 0xd0, 0xea, 0xbe, 0x6f,
	0xd7, 0xaf, 0xb0, 0x78, 0x16, 0x2c, 0x16, 0x5a, 0x83, 0x4b, 0xb4, 0x26, 0x30, 0xda, 0x35, 0x97,
	0xc1, 0x8c, 0xfa, 0x53, 0x67, 0xf6, 0x41, 0x9c, 0x0b, 0x67, 0xc8, 0x82, 0x0e, 0xc8, 0xe6, 0x30,
	0xa8, 0x53, 0xf2, 0x09, 0x3c, 0x25, 0x4f, 0xc6, 0x97, 0x2f, 0xea, 0xb0, 0xae, 0xec, 0x64, 0x61,
	0x6c, 0xf9, 0xa2, 0x0e, 0x17, 0x4f, 0x2e, 0x10, 0xeb, 0xa7, 0x6c, 0x51, 0x1d, 0xf3, 0x1d, 0x92,
	0x25, 0x04, 0x0d, 0xa7, 0x24, 0xe2, 0x7d, 0xff, 0x0b, 0xc6, 0x78, 0x3f, 0xcb, 0xdf, 0x61, 0xd8,
	0x82, 0x45, 0x18, 0xef, 0xa5, 0x94, 0xc5, 0xfc, 0x0a, 0x7e, 0x4b, 0x08, 0x1a, 0x44, 0x48, 0xc4,
	0xfb, 0xb8, 0x62, 0x8c, 0xf7, 0x63, 0xb4, 0x81, 0x61, 0x7b, 0x78, 0x12, 0xf3, 0x7e, 0x40, 0xd8,
	0x84, 0x5f, 0xe1, 0xe3, 0x4f, 0x60, 0xbe, 0x10, 0xdf, 0x9e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe1,
	0xde, 0xe5, 0xfb, 0x36, 0x04, 0x00, 0x00,
}
