// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package movie

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMovieRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieResponse) Reset()         { *m = CreateMovieResponse{} }
func (m *CreateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResponse) ProtoMessage()    {}
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *CreateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResponse.Unmarshal(m, b)
}
func (m *CreateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResponse.Marshal(b, m, deterministic)
}
func (m *CreateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResponse.Merge(m, src)
}
func (m *CreateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResponse.Size(m)
}
func (m *CreateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResponse proto.InternalMessageInfo

func (m *CreateMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{2}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{3}
}

func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(m, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type FindAllMoviesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllMoviesRequest) Reset()         { *m = FindAllMoviesRequest{} }
func (m *FindAllMoviesRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllMoviesRequest) ProtoMessage()    {}
func (*FindAllMoviesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{4}
}

func (m *FindAllMoviesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllMoviesRequest.Unmarshal(m, b)
}
func (m *FindAllMoviesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllMoviesRequest.Marshal(b, m, deterministic)
}
func (m *FindAllMoviesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllMoviesRequest.Merge(m, src)
}
func (m *FindAllMoviesRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllMoviesRequest.Size(m)
}
func (m *FindAllMoviesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllMoviesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllMoviesRequest proto.InternalMessageInfo

type FindAllMoviesResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllMoviesResponse) Reset()         { *m = FindAllMoviesResponse{} }
func (m *FindAllMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllMoviesResponse) ProtoMessage()    {}
func (*FindAllMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{5}
}

func (m *FindAllMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllMoviesResponse.Unmarshal(m, b)
}
func (m *FindAllMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllMoviesResponse.Marshal(b, m, deterministic)
}
func (m *FindAllMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllMoviesResponse.Merge(m, src)
}
func (m *FindAllMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllMoviesResponse.Size(m)
}
func (m *FindAllMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllMoviesResponse proto.InternalMessageInfo

func (m *FindAllMoviesResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type Movie struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{6}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMovieRequest)(nil), "CreateMovieRequest")
	proto.RegisterType((*CreateMovieResponse)(nil), "CreateMovieResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResponse)(nil), "DeleteMovieResponse")
	proto.RegisterType((*FindAllMoviesRequest)(nil), "FindAllMoviesRequest")
	proto.RegisterType((*FindAllMoviesResponse)(nil), "FindAllMoviesResponse")
	proto.RegisterType((*Movie)(nil), "Movie")
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75) }

var fileDescriptor_fde087a4194eda75 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x54, 0x31, 0xe2, 0x8a, 0x18, 0x2e, 0x69, 0x55, 0x45, 0x08, 0x55, 0x16, 0x03,
	0x42, 0xe2, 0x86, 0x66, 0x80, 0x15, 0x81, 0xd8, 0x58, 0xc2, 0x13, 0x00, 0xb9, 0xc1, 0x52, 0xa8,
	0x4b, 0x6c, 0xfa, 0x60, 0x3c, 0x21, 0xea, 0xd9, 0x12, 0x6d, 0xea, 0x81, 0x31, 0x7f, 0xfe, 0xfb,
	0xec, 0xfb, 0x0c, 0xd3, 0x4f, 0xbb, 0x35, 0x4c, 0x9b, 0xc1, 0x7a, 0xab, 0x6f, 0x00, 0x1f, 0x07,
	0x7e, 0xf3, 0xfc, 0xb2, 0x0b, 0x5b, 0xfe, 0xfa, 0x66, 0xe7, 0xb1, 0x82, 0xc2, 0x1b, 0xdf, 0xf3,
	0x22, 0x5b, 0x66, 0xd7, 0xa7, 0x6d, 0xf8, 0xd0, 0x0d, 0x94, 0x07, 0x5d, 0xb7, 0xb1, 0x6b, 0xc7,
	0x78, 0x01, 0x85, 0x10, 0xa5, 0x3c, 0x5d, 0x29, 0x0a, 0xbf, 0x43, 0xa8, 0xaf, 0x00, 0x9f, 0xb8,
	0xe7, 0xd1, 0x01, 0xe7, 0x90, 0x9b, 0x4e, 0x06, 0x26, 0x6d, 0x6e, 0xba, 0x1d, 0xfa, 0xa0, 0xf5,
	0x2f, 0xf4, 0x1c, 0xaa, 0x67, 0xb3, 0xee, 0x1e, 0xfa, 0x5e, 0x62, 0x17, 0xe1, 0xfa, 0x0e, 0x66,
	0xa3, 0x3c, 0xe2, 0x2e, 0x41, 0xc9, 0xa4, 0x5b, 0x64, 0xcb, 0xc9, 0x1e, 0x2f, 0xa6, 0xfa, 0x16,
	0x0a, 0x09, 0xc6, 0xd7, 0xfb, 0xf3, 0x91, 0xef, 0xf9, 0x58, 0xfd, 0x64, 0x70, 0x26, 0xfd, 0x57,
	0x1e, 0xb6, 0xe6, 0x83, 0xb1, 0x01, 0x15, 0x04, 0x61, 0x49, 0xc7, 0x56, 0xeb, 0x8a, 0x52, 0xfa,
	0x1a, 0x50, 0x61, 0x75, 0x2c, 0xe9, 0xd8, 0x54, 0x5d, 0x51, 0x4a, 0xcc, 0x3d, 0x9c, 0xc4, 0x15,
	0x71, 0x46, 0x29, 0x09, 0xf5, 0x9c, 0x92, 0x0e, 0xde, 0x95, 0xbc, 0x7b, 0xf3, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0xbf, 0xdc, 0xaf, 0x06, 0x02, 0x00, 0x00,
}
