// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema_hall.proto

package cinema_hall

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols                 int32    `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CreateRequest) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

type CreateResponse struct {
	Hall                 *CinemaHall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetHall() *CinemaHall {
	if m != nil {
		return m.Hall
	}
	return nil
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{2}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Hall                 *CinemaHall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{3}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetHall() *CinemaHall {
	if m != nil {
		return m.Hall
	}
	return nil
}

type FindAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllRequest) Reset()         { *m = FindAllRequest{} }
func (m *FindAllRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllRequest) ProtoMessage()    {}
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{4}
}

func (m *FindAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllRequest.Unmarshal(m, b)
}
func (m *FindAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllRequest.Marshal(b, m, deterministic)
}
func (m *FindAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllRequest.Merge(m, src)
}
func (m *FindAllRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllRequest.Size(m)
}
func (m *FindAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllRequest proto.InternalMessageInfo

type FindAllResponse struct {
	Halls                []*CinemaHall `protobuf:"bytes,1,rep,name=halls,proto3" json:"halls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FindAllResponse) Reset()         { *m = FindAllResponse{} }
func (m *FindAllResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllResponse) ProtoMessage()    {}
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{5}
}

func (m *FindAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllResponse.Unmarshal(m, b)
}
func (m *FindAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllResponse.Marshal(b, m, deterministic)
}
func (m *FindAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllResponse.Merge(m, src)
}
func (m *FindAllResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllResponse.Size(m)
}
func (m *FindAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllResponse proto.InternalMessageInfo

func (m *FindAllResponse) GetHalls() []*CinemaHall {
	if m != nil {
		return m.Halls
	}
	return nil
}

type CinemaHall struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols                 int32    `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaHall) Reset()         { *m = CinemaHall{} }
func (m *CinemaHall) String() string { return proto.CompactTextString(m) }
func (*CinemaHall) ProtoMessage()    {}
func (*CinemaHall) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{6}
}

func (m *CinemaHall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaHall.Unmarshal(m, b)
}
func (m *CinemaHall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaHall.Marshal(b, m, deterministic)
}
func (m *CinemaHall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaHall.Merge(m, src)
}
func (m *CinemaHall) XXX_Size() int {
	return xxx_messageInfo_CinemaHall.Size(m)
}
func (m *CinemaHall) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaHall.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaHall proto.InternalMessageInfo

func (m *CinemaHall) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CinemaHall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaHall) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CinemaHall) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*FindAllRequest)(nil), "FindAllRequest")
	proto.RegisterType((*FindAllResponse)(nil), "FindAllResponse")
	proto.RegisterType((*CinemaHall)(nil), "CinemaHall")
}

func init() { proto.RegisterFile("cinema_hall.proto", fileDescriptor_48e8c9aa0203f6fd) }

var fileDescriptor_48e8c9aa0203f6fd = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xbb, 0x55, 0x7c, 0x63, 0xed, 0x96, 0x53, 0xe9, 0x65, 0x35, 0xa7, 0x0d, 0x24,
	0xe0, 0xf4, 0x0b, 0xc8, 0x44, 0x04, 0x6f, 0xf1, 0xe2, 0x4d, 0x62, 0xfb, 0xc0, 0x40, 0xd6, 0xcc,
	0xa6, 0xea, 0x47, 0xf1, 0xeb, 0x4a, 0xd2, 0x6e, 0xa5, 0x61, 0x07, 0x6f, 0x8f, 0xff, 0x7b, 0xfc,
	0xde, 0xeb, 0xaf, 0x81, 0x65, 0x29, 0x6b, 0xdc, 0x8b, 0xb7, 0x0f, 0xa1, 0x14, 0x3b, 0x34, 0xba,
	0xd5, 0xf4, 0x19, 0xe6, 0xbb, 0x06, 0x45, 0x8b, 0x1c, 0x3f, 0xbf, 0xd0, 0xb4, 0x84, 0xc0, 0xa4,
	0x16, 0x7b, 0xcc, 0x82, 0x22, 0x58, 0x5f, 0x72, 0x57, 0xdb, 0xac, 0xd1, 0x3f, 0x26, 0x0b, 0x8b,
	0x60, 0x3d, 0xe5, 0xae, 0xb6, 0x59, 0xa9, 0x95, 0xc9, 0xa2, 0x2e, 0xb3, 0x35, 0xbd, 0x81, 0xe4,
	0x08, 0x33, 0x07, 0x5d, 0x1b, 0x24, 0x2b, 0x98, 0xd8, 0x65, 0x8e, 0x36, 0xdb, 0xce, 0xd8, 0xce,
	0x1d, 0xf0, 0x24, 0x94, 0xe2, 0xae, 0x41, 0x57, 0x30, 0x7f, 0x40, 0x85, 0xc3, 0xfe, 0x04, 0x42,
	0x59, 0xb9, 0xf9, 0x88, 0x87, 0xb2, 0xb2, 0xcc, 0xe3, 0xc0, 0x7f, 0x99, 0x0b, 0x48, 0x1e, 0x65,
	0x5d, 0xdd, 0x2b, 0xd5, 0x43, 0xe9, 0x1d, 0xa4, 0xa7, 0xa4, 0xa7, 0x5c, 0xc1, 0xd4, 0x0e, 0x9b,
	0x2c, 0x28, 0x22, 0x1f, 0xd3, 0x75, 0xe8, 0x2b, 0xc0, 0x10, 0xfa, 0x87, 0x9d, 0x44, 0x85, 0x67,
	0x44, 0x45, 0x67, 0x44, 0x4d, 0x06, 0x51, 0xdb, 0xdf, 0x00, 0x96, 0x03, 0xfa, 0x05, 0x9b, 0x6f,
	0x59, 0x22, 0xd9, 0x40, 0xdc, 0xe9, 0x23, 0x09, 0x1b, 0xfd, 0x94, 0x3c, 0x65, 0x9e, 0xd7, 0x0d,
	0xc4, 0x9d, 0x15, 0x92, 0xb0, 0x91, 0xbf, 0x3c, 0x65, 0x9e, 0xae, 0x6b, 0xb8, 0xe8, 0xbf, 0x9d,
	0xa4, 0x6c, 0xec, 0x25, 0x5f, 0x30, 0x4f, 0xcb, 0x7b, 0xec, 0x9e, 0xc5, 0xed, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x01, 0xef, 0x8e, 0x5d, 0x2b, 0x02, 0x00, 0x00,
}
