// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema_hall.proto

package cinema_hall

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCinemaHallRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols                 int32    `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaHallRequest) Reset()         { *m = CreateCinemaHallRequest{} }
func (m *CreateCinemaHallRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaHallRequest) ProtoMessage()    {}
func (*CreateCinemaHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{0}
}

func (m *CreateCinemaHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaHallRequest.Unmarshal(m, b)
}
func (m *CreateCinemaHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaHallRequest.Marshal(b, m, deterministic)
}
func (m *CreateCinemaHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaHallRequest.Merge(m, src)
}
func (m *CreateCinemaHallRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaHallRequest.Size(m)
}
func (m *CreateCinemaHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaHallRequest proto.InternalMessageInfo

func (m *CreateCinemaHallRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCinemaHallRequest) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CreateCinemaHallRequest) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

type CreateCinemaHallResponse struct {
	Hall                 *CinemaHall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateCinemaHallResponse) Reset()         { *m = CreateCinemaHallResponse{} }
func (m *CreateCinemaHallResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaHallResponse) ProtoMessage()    {}
func (*CreateCinemaHallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{1}
}

func (m *CreateCinemaHallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaHallResponse.Unmarshal(m, b)
}
func (m *CreateCinemaHallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaHallResponse.Marshal(b, m, deterministic)
}
func (m *CreateCinemaHallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaHallResponse.Merge(m, src)
}
func (m *CreateCinemaHallResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaHallResponse.Size(m)
}
func (m *CreateCinemaHallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaHallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaHallResponse proto.InternalMessageInfo

func (m *CreateCinemaHallResponse) GetHall() *CinemaHall {
	if m != nil {
		return m.Hall
	}
	return nil
}

type DeleteCinemaHallRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCinemaHallRequest) Reset()         { *m = DeleteCinemaHallRequest{} }
func (m *DeleteCinemaHallRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaHallRequest) ProtoMessage()    {}
func (*DeleteCinemaHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{2}
}

func (m *DeleteCinemaHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaHallRequest.Unmarshal(m, b)
}
func (m *DeleteCinemaHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaHallRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCinemaHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaHallRequest.Merge(m, src)
}
func (m *DeleteCinemaHallRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaHallRequest.Size(m)
}
func (m *DeleteCinemaHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaHallRequest proto.InternalMessageInfo

func (m *DeleteCinemaHallRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCinemaHallResponse struct {
	Hall                 *CinemaHall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteCinemaHallResponse) Reset()         { *m = DeleteCinemaHallResponse{} }
func (m *DeleteCinemaHallResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCinemaHallResponse) ProtoMessage()    {}
func (*DeleteCinemaHallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{3}
}

func (m *DeleteCinemaHallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCinemaHallResponse.Unmarshal(m, b)
}
func (m *DeleteCinemaHallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCinemaHallResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCinemaHallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCinemaHallResponse.Merge(m, src)
}
func (m *DeleteCinemaHallResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCinemaHallResponse.Size(m)
}
func (m *DeleteCinemaHallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCinemaHallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCinemaHallResponse proto.InternalMessageInfo

func (m *DeleteCinemaHallResponse) GetHall() *CinemaHall {
	if m != nil {
		return m.Hall
	}
	return nil
}

type FindAllCinemaHallsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllCinemaHallsRequest) Reset()         { *m = FindAllCinemaHallsRequest{} }
func (m *FindAllCinemaHallsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllCinemaHallsRequest) ProtoMessage()    {}
func (*FindAllCinemaHallsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{4}
}

func (m *FindAllCinemaHallsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllCinemaHallsRequest.Unmarshal(m, b)
}
func (m *FindAllCinemaHallsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllCinemaHallsRequest.Marshal(b, m, deterministic)
}
func (m *FindAllCinemaHallsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllCinemaHallsRequest.Merge(m, src)
}
func (m *FindAllCinemaHallsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllCinemaHallsRequest.Size(m)
}
func (m *FindAllCinemaHallsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllCinemaHallsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllCinemaHallsRequest proto.InternalMessageInfo

type FindAllCinemaHallsResponse struct {
	Halls                []*CinemaHall `protobuf:"bytes,1,rep,name=halls,proto3" json:"halls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FindAllCinemaHallsResponse) Reset()         { *m = FindAllCinemaHallsResponse{} }
func (m *FindAllCinemaHallsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllCinemaHallsResponse) ProtoMessage()    {}
func (*FindAllCinemaHallsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{5}
}

func (m *FindAllCinemaHallsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllCinemaHallsResponse.Unmarshal(m, b)
}
func (m *FindAllCinemaHallsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllCinemaHallsResponse.Marshal(b, m, deterministic)
}
func (m *FindAllCinemaHallsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllCinemaHallsResponse.Merge(m, src)
}
func (m *FindAllCinemaHallsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllCinemaHallsResponse.Size(m)
}
func (m *FindAllCinemaHallsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllCinemaHallsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllCinemaHallsResponse proto.InternalMessageInfo

func (m *FindAllCinemaHallsResponse) GetHalls() []*CinemaHall {
	if m != nil {
		return m.Halls
	}
	return nil
}

type FindCinemaHallRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindCinemaHallRequest) Reset()         { *m = FindCinemaHallRequest{} }
func (m *FindCinemaHallRequest) String() string { return proto.CompactTextString(m) }
func (*FindCinemaHallRequest) ProtoMessage()    {}
func (*FindCinemaHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{6}
}

func (m *FindCinemaHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCinemaHallRequest.Unmarshal(m, b)
}
func (m *FindCinemaHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCinemaHallRequest.Marshal(b, m, deterministic)
}
func (m *FindCinemaHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCinemaHallRequest.Merge(m, src)
}
func (m *FindCinemaHallRequest) XXX_Size() int {
	return xxx_messageInfo_FindCinemaHallRequest.Size(m)
}
func (m *FindCinemaHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCinemaHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindCinemaHallRequest proto.InternalMessageInfo

func (m *FindCinemaHallRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindCinemaHallResponse struct {
	Hall                 *CinemaHall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindCinemaHallResponse) Reset()         { *m = FindCinemaHallResponse{} }
func (m *FindCinemaHallResponse) String() string { return proto.CompactTextString(m) }
func (*FindCinemaHallResponse) ProtoMessage()    {}
func (*FindCinemaHallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{7}
}

func (m *FindCinemaHallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCinemaHallResponse.Unmarshal(m, b)
}
func (m *FindCinemaHallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCinemaHallResponse.Marshal(b, m, deterministic)
}
func (m *FindCinemaHallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCinemaHallResponse.Merge(m, src)
}
func (m *FindCinemaHallResponse) XXX_Size() int {
	return xxx_messageInfo_FindCinemaHallResponse.Size(m)
}
func (m *FindCinemaHallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCinemaHallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindCinemaHallResponse proto.InternalMessageInfo

func (m *FindCinemaHallResponse) GetHall() *CinemaHall {
	if m != nil {
		return m.Hall
	}
	return nil
}

type CinemaHall struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols                 int32    `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaHall) Reset()         { *m = CinemaHall{} }
func (m *CinemaHall) String() string { return proto.CompactTextString(m) }
func (*CinemaHall) ProtoMessage()    {}
func (*CinemaHall) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8c9aa0203f6fd, []int{8}
}

func (m *CinemaHall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaHall.Unmarshal(m, b)
}
func (m *CinemaHall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaHall.Marshal(b, m, deterministic)
}
func (m *CinemaHall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaHall.Merge(m, src)
}
func (m *CinemaHall) XXX_Size() int {
	return xxx_messageInfo_CinemaHall.Size(m)
}
func (m *CinemaHall) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaHall.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaHall proto.InternalMessageInfo

func (m *CinemaHall) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CinemaHall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaHall) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CinemaHall) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateCinemaHallRequest)(nil), "CreateCinemaHallRequest")
	proto.RegisterType((*CreateCinemaHallResponse)(nil), "CreateCinemaHallResponse")
	proto.RegisterType((*DeleteCinemaHallRequest)(nil), "DeleteCinemaHallRequest")
	proto.RegisterType((*DeleteCinemaHallResponse)(nil), "DeleteCinemaHallResponse")
	proto.RegisterType((*FindAllCinemaHallsRequest)(nil), "FindAllCinemaHallsRequest")
	proto.RegisterType((*FindAllCinemaHallsResponse)(nil), "FindAllCinemaHallsResponse")
	proto.RegisterType((*FindCinemaHallRequest)(nil), "FindCinemaHallRequest")
	proto.RegisterType((*FindCinemaHallResponse)(nil), "FindCinemaHallResponse")
	proto.RegisterType((*CinemaHall)(nil), "CinemaHall")
}

func init() { proto.RegisterFile("cinema_hall.proto", fileDescriptor_48e8c9aa0203f6fd) }

var fileDescriptor_48e8c9aa0203f6fd = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0x8f, 0x55, 0x7c, 0x03, 0x61, 0x01, 0xd7, 0x34, 0x3b, 0x58, 0x7b, 0x71, 0x5e,
	0x72, 0x98, 0x07, 0x11, 0x19, 0xa2, 0x13, 0xf1, 0x5c, 0x11, 0xbc, 0x49, 0x6d, 0x1f, 0x58, 0xc8,
	0xda, 0xd9, 0x54, 0xfd, 0x2f, 0xfc, 0x9b, 0x25, 0x69, 0xb1, 0xd2, 0xa5, 0xba, 0xdb, 0xe3, 0x7d,
	0x5f, 0x3f, 0x2f, 0xe1, 0xd3, 0xc0, 0x24, 0xcd, 0x0b, 0x5c, 0x27, 0xcf, 0xaf, 0x89, 0x10, 0x7c,
	0x53, 0x95, 0x75, 0x19, 0x3d, 0x82, 0xbf, 0xaa, 0x30, 0xa9, 0x71, 0xa5, 0xa3, 0xfb, 0x44, 0x88,
	0x18, 0xdf, 0xde, 0x51, 0xd6, 0x84, 0x80, 0x5b, 0x24, 0x6b, 0xa4, 0x56, 0x68, 0xcd, 0xf7, 0x63,
	0x5d, 0xab, 0x5e, 0x55, 0x7e, 0x4a, 0x6a, 0x87, 0xd6, 0x7c, 0x14, 0xeb, 0x5a, 0xf5, 0xd2, 0x52,
	0x48, 0xea, 0x34, 0x3d, 0x55, 0x47, 0x97, 0x40, 0xb7, 0xb1, 0x72, 0x53, 0x16, 0x12, 0xc9, 0x11,
	0xb8, 0xea, 0x00, 0x9a, 0x3b, 0x5e, 0x8c, 0xf9, 0xaf, 0x11, 0x1d, 0x44, 0xa7, 0xe0, 0xdf, 0xa2,
	0x40, 0xd3, 0x99, 0x0e, 0xc0, 0xce, 0x33, 0xfd, 0xa5, 0x13, 0xdb, 0x79, 0xa6, 0xf6, 0x6c, 0x8f,
	0xee, 0xba, 0x67, 0x06, 0xc1, 0x5d, 0x5e, 0x64, 0xd7, 0x42, 0x74, 0x91, 0x6c, 0x37, 0x45, 0x57,
	0xc0, 0x4c, 0x61, 0xcb, 0x3e, 0x86, 0x91, 0x42, 0x48, 0x6a, 0x85, 0x4e, 0x1f, 0xde, 0x24, 0xd1,
	0x09, 0x1c, 0x2a, 0xc0, 0xff, 0x77, 0xb8, 0x80, 0x69, 0x7f, 0x70, 0xd7, 0x1b, 0x3c, 0x01, 0x74,
	0xbd, 0x3e, 0xf8, 0x47, 0xa0, 0x6d, 0x10, 0xe8, 0x18, 0x04, 0xba, 0x9d, 0xc0, 0xc5, 0x97, 0x0d,
	0x93, 0x0e, 0xfd, 0x80, 0xd5, 0x47, 0x9e, 0x22, 0x59, 0x82, 0xd7, 0x68, 0x25, 0x94, 0x0f, 0xfc,
	0x36, 0x2c, 0xe0, 0x83, 0xe6, 0x97, 0xe0, 0x35, 0xb6, 0x08, 0xe5, 0x03, 0x86, 0x59, 0xc0, 0x07,
	0x85, 0xde, 0xc0, 0x5e, 0xab, 0x84, 0x30, 0x3e, 0x68, 0x8e, 0xcd, 0xf8, 0x1f, 0xe2, 0xce, 0xc1,
	0x55, 0x29, 0x99, 0x72, 0xa3, 0x1c, 0xe6, 0x73, 0xb3, 0x8b, 0x17, 0x4f, 0xbf, 0x97, 0xb3, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x47, 0x25, 0xeb, 0x44, 0x03, 0x00, 0x00,
}
